Messages = {
    WELCOME         :0,
    DISPATCH        : 1,
    CONNECTED       : 2,
    LIST            : 3,
    WHO             : 4,
    QUERY           : 5,
    SYNCHRONIZING   : 6,
    SPAWN           : 7,
    DESPAWN         : 8,
    MOVE            : 9,
    DESTROY         : 10,
    ATTACK          : 11,
    EFFECT          : 12,
    CHANGING        : 13,
    TRIGGER         : 14,
    ACTIVE          : 15,
    DEACTIVE        : 16,
    DIE             : 17,
    ROLL            : 18,
    PHASE           : 19,
    END             : 20,
    BOARD           : 21,
    PLAYER          : 22
}