var Messages = {
    WELCOME :0,
    DISPATCH : 1,
    CONNECTED : 2,
    LIST : 3,
    DISCONNECTED : 4,
    SYNCHRONIZING : 5,
    SPAWN : 6,
    DESPAWN : 7,
    MOVE: 8,
    DESTROY : 9,
    ATTACK : 10,
    EFFECT : 11,
    CHANGING : 12,
    TRIGGER : 13,
    ACTIVE: 14,
    DEACTIVE : 15,
    DIE : 16,
    ROLL : 17,
    PHASE : 18,
    END : 19
}